docs/data.rst
docs/input.rst
docs/output.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/conftest.py
test/python/test_rticonnextdds_data_access.py
test/python/test_rticonnextdds_metadata.py
test/python/test_rticonnextdds_output.py
test/python/test_utils.py
test/xml/TestConnector.xml

Also, add test_utils.py module, shared by data_access and the new metadata tester. Add new fixture one_use_input, one_use_output for tests that require a single-use Connector instance

CON-139: Support write options as kwargs; expand support for SampleInfo

---

docs/connector.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/test_rticonnextdds_connector.py
test/python/test_rticonnextdds_data_access.py
test/python/test_rticonnextdds_input.py
test/python/test_rticonnextdds_output.py
test/python/test_utils.py
test/xml/TestConnector.xml

Also changed how errors in entity creation are reported: they are an rti.Error now, and they include the C error messages

CON-146: Test and document not autoenabling readers

---

docs/conf.py
docs/connector.rst
docs/data.rst
docs/getting_started.rst
docs/index.rst
docs/input.rst
docs/output.rst
docs/threading.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/test_rticonnextdds_discovery.py
test/python/test_rticonnextdds_input.py

* Improve threading.rst
* Discovery functions: move some details from rst files to function documentation, so that the rst deals with the most common use case only
* The discovery section in the rst is now after write/read, since waiting/looking up discovery is less important and is optional
* get_matched_publications/subscriptions are now properties instead of methods
* Update doc of write() to indicate that can raise TimeoutError
* Other minor improvemenets

CON-125: Several updates to docs; made discovery methods properties

---

test/python/test_rticonnextdds_connector.py
test/xml/TestConnector.xml

@alexcamposruiz Confirmed that this test currently fails. Tested it with a librtiddsconnectord.so from develop (containing some initial changes in a feature branch to address this bug) and it passes.

CON-214: Added test for creating Connector with participant_qos

---

.gitattributes

With this, License.pdf should not longer show up as changed on Windows

Introduce EOL normalisation

---

test/python/test_rticonnextdds_data_access.py

Changes required after Antonio's fix in native libs.

GREEN-2058: Fixed string checking when setting invalid my_enum from dict

---

docs/copyright_license.rst

required by Legal (they don't care where we put it as long as it's in there)

HERCULES-186: updates to licenses doc for python

---

docs/connector.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/test_rticonnextdds_connector.py

3 static methods have been added to Connector
- version
- Provides the current version of Connector
- native_library_version
- Provides the current version of native libraries being used by Connector
- native_library_build_string
- Provides the build ID of the native libraries being used by Connector

CON-92: Added the ability to obtain current version of Connector

---

rticonnextdds_connector/rticonnextdds_connector.py

The behaviour of max_objects_per_thread has changed in the core, and it now
grows dynamically. There is no longer any reason to allow it to be set in
Connector.

CON-223: Removed ability to set max_objects_per_thread

---

docs/data.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/test_rticonnextdds_data_access.py
test/python/test_rticonnextdds_metadata.py

* CON-191: Added tests for 64-bit int conversions
* CON-191: Added docs
* CON-191: writer's edits to doc changes (py)
* CON-191: Updated tests and docs to reflect new behaviour
I noticed in the native libraries that we weren't being consistent with
the limits. Sometimes we were not checking for v < -LUA_MAX_INT, and sometimes
we were not being consistent with the use of > vs >=.
I have rectified this, the supported behaviour is as follows:
When setting via set_number, we allow |v| < 2^53.
When getting via get_number, we allow |v| <= 2^53.
The reason for the discrepancy between the set and get, is that
when we have a value in set_number, it has already been cast to a double,
so although 2^53 is perfectly representable, we do not know if the original
value was larger (e.g., 2^53 + 1 would …

Con-191, CON-190 merge to 1.1.1 branch

---

docs/release_notes.rst

Adding support for macOS 11 in the release notes.
I redid my changes in a new branch that's based off of develop.

Adding macOS 11 to Connector PY in develop

---

docs/release_notes.rst

Adding macOS 11 to Connector PY in release 1.2.0.
Cherry-picked the change I made in develop: fe90bda

PLATFORMS-2289. Adding macOS 11 to Connector PY release notes in release 1.2.0.

---

docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/index.rst
docs/input.rst

We should make links to core docs go to the specific release. Otherwise, some day when Connector 1.2.0 is old, its links will still go to the latest version of Pro docs, and these may not be appropriate.

CON-252: updating links from current to 6.1.1, py

---

docs/conf.py

I see here that we added the canonical url to develop for js: https://github.com/rticommunity/rticonnextdds-connector-js/pull/66/files
And cherry-picked it to the 1.1.1 release branch for js: https://github.com/rticommunity/rticonnextdds-connector-js/pull/68/files
And I confirmed that I see the canonical url in develop and release/connector/1.2.0 for js. But I do not see it in develop or release/connector/1.2.0 for py. So I am adding it here.

CORE-11993: canonical url added for python connector

---

docs/conf.py
docs/release_notes.rst

@samuelraeburn, we forgot a release note: CON-157. Also, while building these docs, I got an error: I forgot to put a comma after "False" in conf.py when I added the canonical_url.

CON-251: added missing release note and fixed canonical formatting error

---

docs/intro.rst

According to Alex in HMAINT-276, I can count on the Python API URL being like the other API URLs. So although this link to the Python API reference doesn't work yet, it will:
https://community.rti.com/static/documentation/connext-dds/current/doc/api/connext_dds/api_python/intro.html

CON-234: fixing link to Python API reference

---

setup.py

Update reference to rticonnector libraries at 20211203.
Update setup.py to 1.2.0-rc3.
Note: docs/conf.py was *not* updated.
Pending:
Push to testpi.py for install testing
Update just setup.py back to 1.2.0 and push results to production once install testing has completed.

#fix HMAINT-202 -- new connector libraries for python, base on DDS 6.1.1 (20211203)

---

setup.py

Corrected references in rticonnextdds-connector to also point to 1.2.0

#fix HMAINT-202 -- corrected library git references for py, base on DDS 6.1.1 (20211203)

---

docs/conf.py
docs/copyright_license.rst
docs/release_notes.rst

We need to cherry-pick this to release/1.2.0. But what about the other Connector versions?

CON-257: adding Lua vulnerability assessment to Connector 1.2.0 doc

---

setup.py

Candidate release, rc6, for 1.2.0. Here are the _BUILD_ strings for the libraries:
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/libnddsc.so
NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/libnddscore.so
RTICONNECTOR_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm/librtiddsconnector.so
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/libnddsc.so
NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/libnddscore.so
RTICONNECTOR_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-arm64/librtiddsconnector.so
NDDSC_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-x64/libnddsc.so
NDDSCORE_BUILD_6.1.1.0_20220309T000000Z_RTI_REL
found in linux-x64/libnddscore.so …

#fix HMAINT-202 -- new connector libraries for python, base on DDS 6.1.1 (20220309, bkprt)

---

setup.py

Final version string change to 1.2.0.
Note! This version goes directly to production as there is already a 1.2.0 version on test.py!

#fix HMAINT-202 -- final version string 1.2.0

---

rticonnextdds_connector/rticonnextdds_connector.py

Updated loading of windows redistributable.
Updated rticonnextdds-connector submodule to feature/CON-276 branch:
```
Took all builds from BUILD_6.1.2.0_20221014T000000Z_RTI_REL build. All builds are licensed other than armv6.
Architectures used are as follows:
linux-arm: armv6vfphLinux3.xgcc4.7.2
linux-arm64: armv8Linux4.4gcc5.4.0
linux-x64: x64Linux2.6gcc4.4.5
win-x64: x64Win64VS2015
osx-x64: x64Darwin17clang9.0
Other than win-x64, these are identical to the architectures used in 1.2.0. Windows has been updated from VS2013 to VS2015. This meant also updating the redistributable to vcruntime140.dll.
```

CON-276: Updated loading of redist + commit of submodule

---

docs/conf.py
setup.py

Updated git library links to the latest build in the common library repository. Changed docs version to 1.2.2 and bump the rc version to rc2.

CON-278 -- rc2 with libraries from 20221028

---

setup.py

Removing the -rcX from the version string. Double checked libraries and they are all pointing to build NDDSCORE_BUILD_6.1.2.0_20221111T000000Z_RTI_REL.

CON-278 -- final version string for 1.2.2

---

docs/conf.py
docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/index.rst
docs/input.rst
docs/intro.rst
docs/release_notes.rst
rticonnextdds_connector/rticonnextdds_connector.py
setup.py

feature branch based on master. Merged release/connector/1.2.2.
Several doc files have been updated. setup.py and top rticonnextdds-connector.py change too.

CON-285 merge docs and setup.py info back to master.

---

docs/conf.py
docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/index.rst
docs/input.rst
setup.py

This brings branch release/connector/1.2.3 up to date with support/connector/1.2.0 which was just recently updated with release/connector/1.2.2.
From here, we can change version strings, libraries in preparation for the 6.1.2.17 rticonnextdds-connectory-py requirements.

REL-1928 -- merge support/connector/1.2.0 into release/connector/1.2.3

---

docs/conf.py
docs/configuration.rst
docs/connector.rst
docs/data.rst
docs/features.rst
docs/index.rst
docs/input.rst
setup.py

Required for 6.1.2.17, merge latest support/connector/1.2.0, recently updated from release/connector/1.2.2, into release/connector/1.2.3.

REL-1928 -- merge support/connector/1.2.0 -> release/connector/1.2.3

---

setup.py

This is a required change to begin build/test of connext-py for 1.2.3. Using semvar 1.2.3-rc1 as we've done for 1.2.2.
Left all changes of doc/ to documentation, including the version string.

REL-1928 -- update version with first release candidate, 1.2.3-rc1

---

docs/release_notes.rst

I moved the Vulnerability Assessment section to the end of the Release Notes and changed its heading level so it is parallel to Supported Platforms, Version 1.2.3, and Previous Releases.

REL-1995 moving Vulnerability Assessment section 

---

docs/input.rst
rticonnextdds_connector/rticonnextdds_connector.py
test/python/test_rticonnextdds_data_access.py

* Added new `return_samples` method to `Input` class.
* Modify `wait` method to, by default, return the samples.
This requires accessing a new native function, thus requires new native libraries.

CON-314: Allow returning outstanding loans of Inputs, return loan on calling wait

---

README.md
README.rst
docs/conf.py
docs/release_notes.rst
setup.py

Although this repo is deprecated, we still require the merge of release/connector/1.2.3 to the support/connector/1.2.0 support branch. Once approved a new Merge Commit will be created.
DO NOT USE SQUASH!

JH-81 -- apply release/connector/1.2.3 to support/connector/1.2.0, required for future merges.

---

README.md
README.rst
docs/conf.py
docs/release_notes.rst
resources/jenkins/build_and_test.groovy
setup.py

I've created this PR to expose the possible missing progression of release/connector/1.2.4. Could you guys have a look at the diffs and see if they make sense?
Here's what I did ...
```
#
git checkout support/connector/1.2.0 && git pull
git checkout release/connector/1.2.4 && git pull
git checkout -b feature/JH-81-gen-1.2.4-sup-1.2.0
git merge support/connector/1.2.0
git push origin feature/JH-81-gen-1.2.4-sup-1.2.0
```

JH-81 -- late merge of support/connector/1.2.0 back into release/connector/1.2.4

---

docs/conf.py
docs/copyright_license.rst
docs/release_notes.rst

Here is the documentation output associated with this PR: https://jenkins-community.rti.com/job/ci/job/Connector-PY/job/rticonnextdds-connector-py-doc/view/change-requests/job/PR-189/Connector_20Documentation/release_notes.html

REL-2593: updating connector-py release notes for 6.1.2.21
