- README.md
- README.rst
Warn about change in sequence indexing.
Update README.rst to match README.md.
> Fix READMEs

- rticonnextdds_connector/rticonnextdds_connector.py
- test/python/test_rticonnextdds_data_access.py
- test/python/test_rticonnextdds_output.py
Also, review previously xfail tests.
> CON-77: Add test for strings with bad number format in set_dictionary.

- examples/python/ShapeExample.xml
- examples/python/simple/reader.py
- examples/python/simple/writer.py
Also reduced the sleep time when writing and reading
> CON-143: Made type compatible with that in Shapes demo

- rticonnextdds_connector/rticonnextdds_connector.py
> CON-85: Add Connector.set_max_objects_per_thread

- docs/data.rst
- docs/getting_started.rst
- docs/input.rst
- docs/threading.rst
- examples/python/images/image_reader.py
- examples/python/images/image_reader_file.py
- examples/python/simple/reader.py
- examples/python/transformation/reader.py
- examples/python/transformation/transform.py
- rticonnextdds_connector/rticonnextdds_connector.py
- test/python/test_rticonnextdds_data_access.py
- test/python/test_rticonnextdds_data_iterators.py
- test/python/test_rticonnextdds_dataflow.py
- test/python/test_utils.py
The API now is:
for sample in input.samples
for sample in input.samples.valid_data_iter
input.samples[i]
input.samples.count
> CON-119: Changes to sample iterators

- docs/data.rst
- docs/input.rst
- test/python/test_rticonnextdds_metadata.py
- test/xml/TestConnector.xml
Pending changes to librtiddsconnector.so
> CON-188: docs + tests

- docs/data.rst
> CON-188: Fixed code block in docs

- test/python/test_rticonnextdds_threading.py
- test/xml/TestConnector3.xml
@alexcamposruiz The test fails (expected since I haven't fixed it yet). I'm not sure of the actual problem. Do you have any ideas?
> CON-163: Added a unit test for license error (fix is in core)

- docs/features.rst
- docs/release_notes.rst
> Document dependency on Connext version for dynamic libs

- rticonnextdds_connector/rticonnextdds_connector.py
- test/python/test_rticonnextdds_connector.py
(cherry picked from commit 6a0ff37573bd4384d00c7a3e4af5a28c962a808a)
> CON-92 fix for git cloned Connector merge to 1.1.1

- test/python/test_rticonnextdds_connector.py
(cherry picked from commit d7935e283ee96c42d1737e9529b75edc83e7e6a5)
> HMAINT-235: Handle case where build ID contains 4 digits (#96)

- docs/conf.py
- setup.py
libraries and version strings for 1.2.0 test.
> #fix HMAINT-202 -- update libraries for 1.2.0, set version for test.py

- docs/data.rst
> CON-246: Document limitation on Windows with Nan and Infinity

- docs/conf.py
- setup.py
Correct version string for rc1
> HMAINT-202 -- correct malformed version string

- docs/conf.py
- setup.py
this version will replace rc1, which was configured with the wrong version string.
> HMAINT-202 -- set version to rc2 for testing

- examples/python/images/README.md
(cherry picked from commit 77399ad830d7b5d4286d366107a30036cb5554aa)
> CON-253: Document bug in numpy on aarch64 (#113)

- docs/conf.py
- setup.py
Changing version string from 1.2.0-rc2 to 1.2.0
> HMAINT-202 -- set version string to 1.2.0

- docs/conf.py
- setup.py
Adding 1.0.1-rc1 for test up/download of 6.0.1.25 based libraries.
> Version string change to 1.0.1-rc1 for setup and conf

- setup.py
Need to rebuild b/c old libraries are in the rc4 release.
> #fix HMAINT-202 -- clean out old libraries for py.

- docs/conf.py
- setup.py
Final version string change to 1.0.1 from rc1. After approval dist/ files will be created and pushed to test, and if ok, pushed to production.
> #fix SUPPORT-298 -- change version to 1.0.1

- docs/conf.py
- docs/configuration.rst
- docs/connector.rst
- docs/copyright_license.rst
- docs/data.rst
- docs/features.rst
- docs/index.rst
- docs/input.rst
- docs/intro.rst
- docs/release_notes.rst
- examples/python/images/README.md
- rticonnextdds_connector/rticonnextdds_connector.py
- setup.py
- test/python/test_rticonnextdds_connector.py
- test/python/test_rticonnextdds_data_access.py
- test/python/test_rticonnextdds_metadata.py
master updated with the 1.2.0 release
> Final merge of release 1.2.0 to master.

- rticonnextdds_connector/rticonnextdds_connector.py
(cherry picked from commit a0e4f41786952c2297af850227e29d62ba6999de)
> CON-276: Updated loading of redist + commit of submodule (#144)

- setup.py
Change version string in setup.py to 1.2.2
> CON-280-support, change version number to 1.2.2 in support/connector/1.2.0

- setup.py
Move submodule pointer to new libraries. Set release to rc3 so we can test.
> CON-279 -- Update library pointer, and set release to rc3.

- README.md
> CON-313: Update README.md to reflect removal of Connector for Python in 7.3

- README.md
- README.rst
Improving the formatting for the "Note" in README.rst and README.md.
> REL-1995 formatting changes
